### ISSUE TITLE
get items in front-end

### ISSUE THREAD

**Issue by robertnicjoo** [msurguy/laravel-shop-menu#6]
Hi,

How do I get menu in front-end?

I mean when I use

```php
$menus = TopMenu::orderby('order', 'asc')->get();
$topmenu = new TopMenu;
$topmenu = $topmenu->getHTML($menus);
```

I will get `public function buildMenu($menu, $parentid = 0)` from model which is include edit,delete buttons etc. at this point i only need to get menu items in order to show in navbar to users, what should i do?

Thanks.

**Comment by msurguy** [comment]
@robertnicjoo I believe you are asking about how to get this into a Blade template?

**Comment by robertnicjoo** [comment]
Yes, looking for simple variable just like we have `{!! $menu !!}` for admin, same thing for blade instead of looping them. Is there a way to do that?
